In [2]:
import numpy as np

In [3]:
lst=[1,2,3,4]
arr=np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(4,)

In [6]:
lst1=[1,2,3,4]
lst2=[2,3,4,5]
lst3=[4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [7]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [8]:
arr1.shape

(3, 4)

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
#indexing
arr[3]

np.int64(4)

In [11]:
arr[3]=5

In [12]:
arr

array([1, 2, 3, 5])

In [13]:
arr[1:2]

array([2])

In [14]:
arr[:-1]

array([1, 2, 3])

In [15]:
arr[-1]

np.int64(5)

In [16]:
arr[::-2]

array([5, 2])

In [17]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [18]:
arr1[:,1] # esme pura colom utaega 1 wala

array([2, 3, 5])

In [19]:
arr1[:,3:]

array([[4],
       [5],
       [7]])

In [20]:
#EDA
arr

array([1, 2, 3, 5])

In [21]:
arr<3

array([ True,  True, False, False])

In [22]:
arr[arr<2]

array([1])

In [23]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [24]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 4],
       [5, 6, 7]])

In [25]:
#mechanism to create an array
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [33]:
np.arange(1,3,2).reshape(1,1)

array([[1]])

In [34]:
arr* arr

array([ 1,  4,  9, 25])

In [35]:
arr1 * arr1

array([[ 1,  4,  9, 16],
       [ 4,  9, 16, 25],
       [16, 25, 36, 49]])

In [36]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.random.randint(10,50)

31

In [45]:
np.random.randint(10,50,4)

array([45, 19, 11, 22], dtype=int32)

In [46]:
np.random.randint(10,50,4).reshape(2,2)

array([[27, 26],
       [19, 32]], dtype=int32)

In [47]:
np.random.randn(5,6)

array([[ 0.47282342, -0.34587866, -1.4002759 ,  0.10214408, -0.29643115,
         0.86870113],
       [ 0.96785224, -0.73047566, -1.15301753,  0.58090901, -0.67121177,
        -1.31876404],
       [ 0.48215933, -0.30852605, -0.54534111, -0.21067819,  1.35257616,
         0.12170977],
       [ 0.9033757 , -1.62184242, -0.44650082, -1.86311924, -2.2765084 ,
         0.55863322],
       [-0.78784021, -0.54040552,  0.29691451, -0.54657021, -0.21069765,
         0.58506753]])

In [49]:
np.random.random_sample((4,7))

array([[0.91831335, 0.30427315, 0.07794086, 0.69787349, 0.30049292,
        0.58225727, 0.83099984],
       [0.3459731 , 0.9425295 , 0.54568328, 0.53551141, 0.1564296 ,
        0.59410045, 0.18037682],
       [0.75549658, 0.47888846, 0.1486424 , 0.0900378 , 0.49339314,
        0.54637895, 0.54601858],
       [0.23442675, 0.05076457, 0.99637213, 0.06887137, 0.0318274 ,
        0.5575782 , 0.31312267]])