1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
np.arange(0,20).reshape(5,4) # ese ham 2 dimensional data bolte h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
#create Dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["column1","column2","column3","column4"])

In [12]:
df.head() # top ka five record deta h dataframe ka

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [13]:
df.tail() #last ka five record deta h

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [14]:
df.info()# yah information deta h ki column ka datatype kya hota h

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int64
 1   column2  5 non-null      int64
 2   column3  5 non-null      int64
 3   column4  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [15]:
df.describe() # jo column int ya float type ka hote h bo hii select honge yaha p

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [16]:
#### INDEXING
#columnname,rowindex[Loc],rowindex columnindex number[.iloc]

In [17]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [19]:
## columnname
df['column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: column1, dtype: int64

In [20]:
df[['column1','column2','column3']] #jab multiple column ho tab ya nasted list lete h mtlb double brackets

column1  column2  column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [21]:
#using row index name Loc
df.loc['Row3']

column1     8
column2     9
column3    10
column4    11
Name: Row3, dtype: int64

In [22]:
df.loc[['Row2','Row3']]

column1  column2  column3  column4
Row2        4        5        6        7
Row3        8        9       10       11

In [23]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [24]:
df.iloc[2:4,0:2] #[row,column]

column1  column2
Row3        8        9
Row4       12       13

In [25]:
df.iloc[2:,1:]

column2  column3  column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [26]:
#convert dataframe into arrays
df.iloc[2:,1:].values

array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [27]:
# Basic opertions
df.isnull().sum() #null value find kata h

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [28]:
df['column3'].value_counts() #yah value batata h ki column ma ek value kitne barr present h

column3
2     1
6     1
10    1
14    1
18    1
Name: count, dtype: int64

In [29]:
df['column2'].unique()

array([ 1,  5,  9, 13, 17])

In [31]:
df[df['column2']>2]

column1  column2  column3  column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19